### PR TITLE
Update apache-arrow for 2.0.0

### PR DESCRIPTION
**Pull request by nealrichardson**
cf. https://github.com/r-windows/rtools-packages/pull/160

### CODE REVIEW

**Comment by jeroen** [comment]
Is there any way to disable avx512 on unsupported compilers, so that we can build on osx 10.11?

I already tried to cheat by using the 10.13 libarrow binaries to build the R package on 10.11, however that results in a linking error `Symbol not found: _os_unfair_lock_lock` for something in `libarrow_bundled_dependencies.a` (probably jemalloc).

**Comment by nealrichardson** [comment]
Given https://github.com/apache/arrow/blob/master/cpp/cmake_modules/DefineOptions.cmake#L107-L122, it looks like we can set `ARROW_RUNTIME_SIMD_LEVEL` to something less--what would be appropriate, AVX2?

Presumably though if the compiler doesn't support AVX512 then we shouldn't be using it, so that suggests that the check for support (here I think? https://github.com/apache/arrow/blob/master/cpp/cmake_modules/SetupCxxFlags.cmake#L55) isn't doing the right thing for this compiler.

**Comment by jeroen** [comment]
Yeah let's try that, see what the CI says.

**Comment by jeroen** [comment]
Same error... looks like `util/bpacking_avx512.cc` is included unconditionally.

I think you need to condition that on ARROW_RUNTIME_SIMD_LEVEL as done here: https://github.com/apache/arrow/blob/44f3de2c2854a473d4ce184e02c4db83dffb805d/cpp/cmake_modules/SetupCxxFlags.cmake#L73

**Comment by nealrichardson** [comment]
You mean something like this? https://github.com/apache/arrow/commit/699d702c30da5582b82e6136afe9a10903f5c695

**Comment by nealrichardson** [comment]
That appears to have allowed `brew install` to succeed

**Comment by jeroen** [comment]
Perfect, thanks!

**Pull request merged**
