### PR TITLE
apache-arrow 0.14.1

### PR DESCRIPTION
**Pull request by nealrichardson**
- [ ] Have you followed the [guidelines for contributing](https://github.com/Homebrew/homebrew-core/blob/master/CONTRIBUTING.md)?
- [x] Have you checked that there aren't other open [pull requests](https://github.com/Homebrew/homebrew-core/pulls) for the same formula update/change?
- [ ] Have you built your formula locally with `brew install --build-from-source <formula>`, where `<formula>` is the name of the formula you're submitting?
- [ ] Does your build pass `brew audit --strict <formula>` (after doing `brew install <formula>`)?

-----

### CODE REVIEW

**Comment by jeroen** [comment]
You need to actually build the bottle, otherwise this won't work :)

**Comment by nealrichardson** [comment]
Alright. Can you teach me how best to update this formula? Would it be acceptable to just copy https://github.com/Homebrew/homebrew-core/blob/master/Formula/apache-arrow.rb, which has been updated for 0.14.1 and has bottle SHAs?

**Comment by jeroen** [comment]
It's a bit tricky, I have a special VM setup to do this. But does the R package really benefit from 0.14.0 to 0.14.1 or are we just doing this for fun?

**Comment by nealrichardson** [comment]
The main reason for the [0.14.1 arrow release](https://arrow.apache.org/release/0.14.1.html) was to resolve an issue in the Parquet library (https://issues.apache.org/jira/browse/ARROW-5889 and https://issues.apache.org/jira/browse/ARROW-5878). So R users would benefit from this because it would prevent them from data loss when writing to Parquet.

**Comment by jeroen** [comment]
Fixed via https://github.com/autobrew/homebrew-core/commit/13a6bbf1e769392aa365cf8a34206f2187810778.

By the way: this is not an official repo. The autobrew system is a bit of a hack to build and download libs for macos because it is very hard to convince CRAN maintainers to install libs on the server.

I'm surprised you found it :D

**Comment by nealrichardson** [comment]
Thanks! Yeah I noticed it in the arrow `configure` script and figured as much 🤐

**Pull request closed without merging**
