### PR TITLE
apache-arrow 1.0.1

### PR DESCRIPTION
**Pull request by nealrichardson**
See also https://github.com/r-windows/rtools-packages/pull/142

### CODE REVIEW

**Comment by jeroen** [comment]
Maybe try with your patch?

**Comment by jeroen** [comment]
Still failing. It looks like our recent cmake update is affecting the build process. Maybe try without unity? Perhaps unity wasn't actually used before because previously our cmake was old.

**Comment by jeroen** [comment]
So the flags you added to the test are redundant I think?

**Comment by nealrichardson** [comment]
Yeah they're probably not necessary, can try without them

**Comment by nealrichardson** [comment]
Thanks @jeroen

**Pull request merged**
