### PR TITLE
Bump for arrow 0.17.1

### PR DESCRIPTION
**Pull request by nealrichardson**

### CODE REVIEW

**Comment by jeroen** [comment]
Yay the CI actually worked.

**Comment by jeroen** [comment]
I can't merge this because the mirror is 404. Can we just use the original url?

**Comment by nealrichardson** [comment]
You'd think that their mirror resolving service would pick a mirror that actually has the requested file...

I tried adding a `mirror` URL to the formula; let's see if that works. According to https://downloads.apache.org/, Apache really wants that only to be a last resort.

**Comment by jeroen** [comment]
It's still saying: `Error: Download failed: Couldn't determine mirror, try again later.`.

**Comment by jeroen** [comment]
Maybe the apache mirror router has blocked travis? I have no idea what's going on. I think it's silly to use a mirroring script here, it's not like autobrew generates any traffic to the apache site. This is basically a one-off build.

**Pull request merged**
