### PR TITLE
Arrow 7.0

### PR DESCRIPTION
**Pull request by wjones127**

### CODE REVIEW

**Comment by jeroen** [comment]
Looks like the vendored version of mimalloc does not work on macos 10.13. We can either downgrade or disable mimalloc.

**Comment by wjones127** [comment]
Thanks for doing that @jeroen! Looks like it built successfully.

**Comment by jeroen** [comment]
FYI, i'll be offline next week, so I won't be able to merge and deploy this before Sunday feb 6. Please don't submit the R package to cran before that :-)

Also please don't submit too many PR's to this repo in the mean while, because we have limited travis-CI credits and they are very expensive :) The other repos ([homebrew-cran](https://github.com/autobrew/homebrew-cran) and the r-windows repos) only use free CI services, so you can test there as much as you want.

**Comment by jeroen** [comment]
OK I have deployed and tested all the windows/macos binaries. You can submit the R package to CRAN.

**Pull request merged**
