### PR TITLE
arrow 4.0.0

### PR DESCRIPTION
**Pull request by jonkeane**
See also r-windows/rtools-packages#197

### CODE REVIEW

**Comment by jeroen** [comment]
Can you remove the patch from the formula that we added for 3.0.0?

**Comment by jonkeane** [comment]
Done, sorry about that. I misread the issue associated with that and thought that it was still necessary.

**Comment by jeroen** [comment]
Ok thanks. Everything looking good 👍

**Comment by jonkeane** [comment]
If I'm reading this correctly, the travis errors are only:

```
brew audit autobrew/core/apache-arrow --online
...
Error: 1 problem in 1 formula detected
734apache-arrow:
735  * Stable version URLs should not contain rc1
```

which make sense given these are our RC tests. Is there anything else indicating I should change something to be ready when we have the full release ready?

**Comment by jeroen** [comment]
No, everything looks good to go. I'll merge it once you update the PR to the final URL.

**Pull request merged**
