### PR TITLE
arrow 6.0.0

### PR DESCRIPTION
**Pull request by jeroen**

### CODE REVIEW

**Comment by jonkeane** [comment]
We think [the error from travis](https://app.travis-ci.com/github/autobrew/homebrew-core/jobs/544705672#L779) might be solveable with the following patch

```
index fd179a8bf..bc48ae76c 100644
--- a/cpp/src/arrow/util/key_value_metadata.cc
+++ b/cpp/src/arrow/util/key_value_metadata.cc
@@ -56,6 +56,8 @@ static std::vector<std::string> UnorderedMapValues(
   return values;
 }

+KeyValueMetadata::KeyValueMetadata() {}
+
 KeyValueMetadata::KeyValueMetadata(
     const std::unordered_map<std::string, std::string>& map)
     : keys_(UnorderedMapKeys(map)), values_(UnorderedMapValues(map)) {
diff --git a/cpp/src/arrow/util/key_value_metadata.h b/cpp/src/arrow/util/key_value_metadata.h
index 2a31bf378..ba70ffe88 100644
--- a/cpp/src/arrow/util/key_value_metadata.h
+++ b/cpp/src/arrow/util/key_value_metadata.h
@@ -34,7 +34,7 @@ namespace arrow {
 /// \brief A container for key-value pair type metadata. Not thread-safe
 class ARROW_EXPORT KeyValueMetadata {
  public:
-  KeyValueMetadata() = default;
+  KeyValueMetadata();
   KeyValueMetadata(std::vector<std::string> keys, std::vector<std::string> values);
   explicit KeyValueMetadata(const std::unordered_map<std::string, std::string>& map);
```

We have [a PR for that as well](https://github.com/apache/arrow/pull/11526), so if it's easier for us to merge it and create a new bundle instead of as a patch in the formula, let us know.

**Comment by jeroen** [comment]
Actually it isn't very important, as this only happens on macos 10.11 but the CRAN servers user macOS 10.13 these days. I just need to update my CI.

**Comment by jeroen** [comment]
Looks like your patch fixed the 10.11 build as well 👍

**Comment by jeroen** [comment]
Merging this even though the vote officially hasn't closed yet, to unblock the release of the R package as I am on vacation next week. If the vote does not pass I will update the binaries when I get back from vacation.

**Pull request closed without merging**
