### PR TITLE
Add brotli and bz2 to apache-arrow

### PR DESCRIPTION
**Pull request by wjones127**

### CODE REVIEW

**Comment by nealrichardson** [comment]
@wjones127 looks like there is no autobrew bottle for brotli: https://app.travis-ci.com/github/autobrew/homebrew-core/builds/252645393#L342

**Comment by wjones127** [comment]
Yeah. Not sure I understand what do do about that. Where are they generated? There is a definition in this repo for brotli for high sierra: https://github.com/autobrew/homebrew-core/blob/high-sierra/Formula/brotli.rb

**Comment by jeroen** [comment]
I have backported a copy of brotli: https://github.com/autobrew/homebrew-core/commit/3d7068db82e0a382dee86e9dfb383d50c0f233c8. The build passes now.

**Comment by jeroen** [comment]
Superseded by https://github.com/autobrew/homebrew-core/pull/114

**Pull request closed without merging**
